"""create orders table

Revision ID: 72a10783d06a
Revises: 
Create Date: 2026-09-26 01:57:12.011989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72a10783d06a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('reward', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('supplier_id', sa.String(), nullable=False),
    sa.Column('pickup_location', sa.Text(), nullable=False),
    sa.Column('delivery_location', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), server_default='open', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_supplier_id'), 'orders', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_orders_supplier_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
